### ISSUE TITLE
Send local information to GitHub in Exercise 7 does not send anything

### ISSUE THREAD

**Issue by AnnikaLau** [C2SM/git-course#100]

**Comment by fabianschoeni** [comment]
Since we expect people to set up their SSH keys at the beginning of the course, should we remove the part about HTTPS tokens? This would also solve #69

**Comment by mjaehn** [comment]
For the sake of simplicity, I would say yes. The users would anyway have to create an SSH key if they continue to work with git / GitHub.

**Comment by jonasjucker** [comment]
I disagree with the conclusion.

We did not use ssh-keys in the past because participants might use the IAC-notebooks.
For security reasons it is safer to use the access-tokens through https, since you can limit the scope of the token to a specific repo.

Also this did not cause problems in the past, but I am sure generating the ssh-key and adding them to GitHub is more difficult.

So why not leave this part as is?

**Comment by mjaehn** [comment]
> We did not use ssh-keys in the past because participants might use the IAC-notebooks.

Yes indeed, we had 2-3 users who didn't manage to run a local installation. Let's keep the tokens, but move them outside the exercise. Maybe create a separate file with information about tokens and ssh key and link to it within the exercise.

Afterwards, review this exercise. The point if this issue is that there might be something missing.

**Comment by AnnikaLau** [comment]
> > We did not use ssh-keys in the past because participants might use the IAC-notebooks.
> 
> Yes indeed, we had 2-3 users who didn't manage to run a local installation. Let's keep the tokens, but move them outside the exercise. Maybe create a separate file with information about tokens and ssh key and link to it within the exercise.
> 
> Afterwards, review this exercise. The point if this issue is that there might be something missing.

What do you think about this https://github.com/C2SM/git-course/pull/103?
