### ISSUE TITLE
Add .ipynb_checkpoints to .gitignore in the initialised Git repositories by the helper function

### ISSUE THREAD

**Issue by AnnikaLau** [C2SM/git-course#66]

**Comment by fabianschoeni** [comment]
We could do something like this: 

```
git init
echo ".ipynb_checkpoints/" >> .gitignore
git add .gitignore && git commit -m "Add .gitignore"
```

**Comment by fabianschoeni** [comment]
addeb15b1c9d73ece407f2a2bee35829d0f8f150 adds the ipynb_checkpoints to the .gitignore for git repo's that are initialised within the helpers.sh.

**Comment by fabianschoeni** [comment]
In exercise 4 the users do the [git init](https://github.com/C2SM/git-course/blob/46900a2415b86ad99546300fa80287fc2dce983a/beginner/Exercise_4/Exercise_4.ipynb#L112) themselves. We should think about adding an extra cell to 1. explain to users what a .gitignore is and why we need to echo .ipynb checkpoints into the .gitignore, and 2. show how this works. Otherwise, we could take the git init from the notebook and add it along with the .gitignore creation directly to the [init_repo_empty_schedule](https://github.com/C2SM/git-course/blob/46900a2415b86ad99546300fa80287fc2dce983a/beginner/helpers.sh#L24C1-L24C29) function in helpers.sh.

**Comment by AnnikaLau** [comment]
I think we should add a short explanation of `.gitignore` in Exercise 1 and then repeat it in Exercise 4. It is a quite commonly used feature in Git. What do you think?

**Comment by fabianschoeni** [comment]
> I think we should add a short explanation of `.gitignore` in Exercise 1 and then repeat it in Exercise 4. It is a quite commonly used feature in Git. What do you think?

I fully agree, that would make sense!

**Comment by fabianschoeni** [comment]
Forgot to write it down...what did we agree here again? Introduce the `.gitignore` feature in Exercise 4? And is it fine if we do this right after the `git init` cell with an echo followed by a git commit?

**Comment by AnnikaLau** [comment]
Yes, but we will need to adapt the introduction text to Exercise 4 for that, as we are now introducing something new.
Maybe we can introduce it right after git init and as soon as they the checkpoint file, they have a use case and can try it out with that?

**Comment by mjaehn** [comment]
LGTM
