### ISSUE TITLE
Extend the course past lunch

### ISSUE THREAD

**Issue by jonasjucker** [C2SM/git-course#77]
Some participants did not have enough time for the excercises. Do a proper lunch break might help.

**Comment by AnnikaLau** [comment]
@jonasjucker, @mjaehn (as you were at last year's course): what do you think of this issue? Does a longer course make sense? We should decide that soon as I want to send out the announcement.

**Comment by mjaehn** [comment]
I think we are sometimes a bit in a rush. First of all, as @jonasjucker mentioned, because of the exercises, but we also lost time due to technical issues (access to JupyterLab, can be avoided) and people having not set up their environment correctly.

It would also fit content-wise, as we could have a lunch break after Part 4 and then continue with all the "remote git" parts afterwards.

I suggest we try this for this year and see how it goes.

**Comment by jonasjucker** [comment]
Yes let's give it a try

**Comment by AnnikaLau** [comment]
So, we extend the course by 2 hours of which 1 hour the lunch break is? Let's say 9:00 - 14:30?

**Comment by AnnikaLau** [comment]
The [schedule](https://github.com/C2SM/git-course/blob/main/beginner/schedule.md) still needs to be updated

**Comment by mjaehn** [comment]
Done in https://github.com/C2SM/git-course/commit/3b05dd50ed6daa13a8678228b6089bb13fc96c03
